{% set name = "muttlib" %}
{% set version = "1.4.27" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muttlib-{{ version }}.tar.gz
  sha256: 770226cfba9a96124c56de5f254777229bbf395c47856d7fd59051a979dc8903

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.10
  run:
    - deprecated >=1.2.13,<2.0.0
    - ipython >=7.29.0,<8.0.0
    - jinja2 >=2.11.3,<3.1.0
    - jinjasql >=0.1.8,<0.2.0
    - lxml >=4.9.1
    - matplotlib-base >=3.5.0,<4.0.0
    - markupsafe >=0.2.3,<2.1.0
    - numpy >=1.20.0,<2.0
    - pandas >=1.0.0
    - pillow >=9.1.1
    - progressbar2 >=3.55.0,<4.0.0
    - pyjwt >=2.4.0
    - python >=3.6,<3.10
    - pyyaml >=5.1,<7.0
    - scikit-learn >=1.0.1,<2.0.0
    - scipy >=1.7.2,<2.0.0
    - sqlalchemy >=1.3.0,<1.4.0
    - types-pymysql >=1.0.11,<2.0.0
    - types-requests >=2.27.7,<3.0.0
    - ujson >=5.4.0
    - wrapt ==1.11.2

test:
  imports:
    - muttlib
    - muttlib.dbconn
    - muttlib.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/mutt_data/muttlib/
  summary: Collection of helper modules by Mutt Data.
  doc_url: https://mutt_data.gitlab.io/muttlib/
  # license packaged in manually for now; added PR upstream
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
