{% set name = "muttlib" %}
{% set version = "1.4.13.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muttlib-{{ version }}.tar.gz
  sha256: b5d9158a5fbda0bb09250831e74462f216ab809cf251ec2e5102a19fcecf3e55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.10
  run:
    - deprecated >=1.2.13,<2.0.0
    - ipython >=7.29.0,<8.0.0
    - jinja2 >=3.0.3,<4.0.0
    - jinjasql >=0.1.8,<0.2.0
    - matplotlib-base >=3.5.0,<4.0.0
    - numpy >=1.20.0,<2.0
    - pandas >=1.0.0
    - progressbar2 >=3.55.0,<4.0.0
    - python >=3.6,<3.10
    - pyyaml >=6.0,<7.0
    - scikit-learn >=1.0.1,<2.0.0
    - scipy >=1.7.2,<2.0.0
    - sqlalchemy >=1.3.0,<1.4.0
    - types-pymysql >=1.0.11,<2.0.0
    - types-requests >=2.27.7,<3.0.0
    - wrapt ==1.11.2

test:
  imports:
    - muttlib
    - muttlib.dbconn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MuttData/muttlib
  summary: Collection of helper modules by Mutt Data.
  doc_url: https://mutt_data.gitlab.io/muttlib/
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
