{% set name = "muttlib" %}
{% set version = "1.4.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muttlib-{{ version }}.tar.gz
  sha256: 9d83b76068c007dd0f960888ea67c04693c63e85588ddbbb58ab0c1cc734e660

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<3.11
  run:
    - python >=3.8,<3.11
    - deprecated >=1.2.13,<2.0.0
    - pandas >=1.0.0
    - progressbar2 >=3.55.0,<4.0.0
    - pyyaml >=5.1,<7.0
    - scikit-learn >=1.0.1,<2.0.0
    - scipy >=1.7.2,<2.0.0
    - sqlalchemy >=1.3,<2.0
    - numpy >=1.22.0,<2.0
    - jinjasql >=0.1.8,<0.2.0
    - ipython >=8.0.1
    - matplotlib-base >=3.5.0,<4.0.0
    - types-requests >=2.27.7,<3.0.0
    - types-pymysql >=1.0.11,<2.0.0
    - jinja2 >=2.11.3,<3.1.0
    - markupsafe >=0.2.3,<2.1.0
    - pillow >=9.1.1
    - ujson >=5.4.0
    - pyjwt >=2.4.0
    - lxml >=4.9.1

test:
  imports:
    - muttlib
    - muttlib.dbconn
    - muttlib.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/mutt_data/muttlib/
  summary: Collection of helper modules by Mutt Data.
  doc_url: https://mutt_data.gitlab.io/muttlib/
  # license packaged in manually for now; added PR upstream
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
