{% set name = "muttlib" %}
{% set version = "1.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muttlib-{{ version }}.tar.gz
  sha256: 066948dc9068e4f6320bada9d72f2ca9ce63a3a37b84bb5243e8a1b77d93b5ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deprecated
    - ipython
    - jinja2
    - jinjasql
    - matplotlib-base
    - numpy ==1.19.5
    - pandas >=1.0.0
    - progressbar2
    - python >=3.6
    - pyyaml
    - scikit-learn
    - scipy
    - sqlalchemy <1.4.0,>=1.3.0

test:
  imports:
    - muttlib
    - muttlib.dbconn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MuttData/muttlib
  summary: Collection of helper modules by Mutt Data.
  doc_url: https://mutt_data.gitlab.io/muttlib/
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
