{% set name = "muttlib" %}
{% set version = "1.4.10.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/muttlib-{{ version }}.tar.gz
  sha256: 1956f3470461c4eb04b155663c21cbb3b2e9104e56c1f76e541e9137012032c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deprecated
    - ipython
    - jinja2
    - jinjasql
    - matplotlib-base
    - numpy <2.0,>=1.20.0
    - pandas >=1.0.0
    - progressbar2
    - python >=3.6
    - pyyaml
    - scikit-learn
    - scipy
    - sqlalchemy <1.4.0,>=1.3.0

test:
  imports:
    - muttlib
    - muttlib.dbconn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MuttData/muttlib
  summary: Collection of helper modules by Mutt Data.
  doc_url: https://mutt_data.gitlab.io/muttlib/
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
